version: '3'
services:

  db:
    image: "postgres:9.6-alpine"
    container_name: db
    volumes:
      - data:/var/lib/postgresql/data
    expose:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=wojsko38
    networks:
      - back

  backend:
    build: ./spring-boot-server
    container_name: backend
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=wojsko38
      - SPRING_JPA_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - BEZKODER_APP_JWTSECRET=bezKoderSecretKey
      - BEZKODER_APP_JWTEXPIRATIONMS=86400000
    ports:
      - 8080:8080
    networks:
      - back

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - 4200:4200
    networks:
      - back
    depends_on:
      - backend

networks:
  back: {}

volumes:
  data: